# Generated by Django 3.1.7 on 2021-10-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbnuser',
            name='phone',
            field=models.TextField(default='', verbose_name='phone'),
            preserve_default=False,
        ),
    ]
