# Generated by Django 3.1.7 on 2021-10-11 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_district',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Район')),
            ],
        ),
        migrations.CreateModel(
            name='Address_locality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Населенный пункт')),
            ],
        ),
        migrations.CreateModel(
            name='Address_region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Область')),
            ],
        ),
        migrations.CreateModel(
            name='Address_street',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название улицы')),
            ],
        ),
        migrations.CreateModel(
            name='Deal_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип сделки')),
            ],
        ),
        migrations.CreateModel(
            name='Object_kind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назначение')),
            ],
        ),
        migrations.CreateModel(
            name='Object_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип объекта')),
            ],
        ),
        migrations.CreateModel(
            name='Object_types_and_kinds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_kind', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.object_kind', verbose_name='Назначение')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.object_type', verbose_name='Тип объекта')),
            ],
            options={
                'unique_together': {('object_kind', 'object_type')},
            },
        ),
        migrations.CreateModel(
            name='Object_address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_string', models.TextField(blank=True, null=True, verbose_name='исходная текстовая строка')),
                ('object_number', models.CharField(blank=True, max_length=70, null=True, verbose_name='Номер дома, квартиры и пр.')),
                ('address_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.address_district', verbose_name='Район')),
                ('address_locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.address_locality', verbose_name='Населенный пункт')),
                ('address_region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.address_region', verbose_name='Область')),
                ('address_street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.address_street', verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Advt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100, verbose_name='Источник')),
                ('source_id', models.CharField(max_length=20, verbose_name='Id в источнике')),
                ('placement_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('download_date', models.DateTimeField(verbose_name='Дата парсинга')),
                ('original_link', models.URLField(verbose_name='Ссылка на исходное размещение объекта')),
                ('square', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Площадь объекта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена объекта')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Удельная цена')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('deal_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.deal_type')),
                ('object_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.object_address')),
                ('object_types_and_kinds', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.object_types_and_kinds')),
            ],
        ),
    ]
