# Generated by Django 3.1.7 on 2021-10-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAccess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='original_link',
            field=models.URLField(max_length=300, verbose_name='Ссылка на исходное размещение объекта'),
        ),
    ]
