# Generated by Django 3.1.7 on 2022-03-08 06:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataAccess', '0002_auto_20211015_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Источник')),
            ],
        ),
        migrations.AddField(
            model_name='advt',
            name='source_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataAccess.source'),
        ),
    ]
