# Generated by Django 3.1.7 on 2022-03-08 06:39

from django.db import migrations


def link_source(apps, schema_editor):
    Advt = apps.get_model('dataAccess', 'Advt')
    Source = apps.get_model('dataAccess', 'Source')
    for advt in Advt.objects.all():
        source, created = Source.objects.get_or_create(name=advt.source)
        advt.source_link = source
        advt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dataAccess', '0003_auto_20220308_0638'),
    ]

    operations = [
        migrations.RunPython(link_source),
    ]
