# Generated by Django 4.1.5 on 2023-03-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAccess', '0005_remove_advt_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object_address',
            unique_together={('raw_string', 'address_region', 'address_locality', 'address_district', 'address_street', 'object_number')},
        ),
    ]
